dbMemo "SQL" ="SELECT tblPeriod.perID, Sum(IIf([trnsSign]='C',-1*[trnsAmount],[trnsAmount])) AS"
    " Bal, tblAccount.accID\015\012FROM tblAccount INNER JOIN (tblTransactionSub INNE"
    "R JOIN (tblTransaction INNER JOIN (tblPeriodSel INNER JOIN tblPeriod ON tblPerio"
    "dSel.perID = tblPeriod.perID) ON tblTransaction.persID = tblPeriodSel.persID) ON"
    " tblTransactionSub.trnID = tblTransaction.trnID) ON tblAccount.accID = tblTransa"
    "ctionSub.accID\015\012WHERE tblAccount.accID = 138 AND tblTransaction.trnYear in"
    " (SELECT yearID FROM tblControl)\015\012GROUP BY tblPeriod.perID, tblAccount.acc"
    "ID\015\012ORDER BY tblPeriod.perID;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
