dbMemo "SQL" ="SELECT tblChart.coaID, tblChart.coaNo, tblChart.coaName, Choose(tblChart.lvlID,L"
    "eft(Right(\"0\" & CStr(tblChart.coaRef\\1000000),2) & \"-\" & Right(\"0\" & CStr"
    "((tblChart.coaRef\\10000) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tblChart.coa"
    "Ref\\100) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tblChart.coaRef) Mod 100),2)"
    ",2),Left(Right(\"0\" & CStr(tblChart.coaRef\\1000000),2) & \"-\" & Right(\"0\" &"
    " CStr((tblChart.coaRef\\10000) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tblChar"
    "t.coaRef\\100) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tblChart.coaRef) Mod 10"
    "0),2),5),Left(Right(\"0\" & CStr(tblChart.coaRef\\1000000),2) & \"-\" & Right(\""
    "0\" & CStr((tblChart.coaRef\\10000) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tb"
    "lChart.coaRef\\100) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tblChart.coaRef) M"
    "od 100),2),8),Right(\"0\" & CStr(tblChart.coaRef\\1000000),2) & \"-\" & Right(\""
    "0\" & CStr((tblChart.coaRef\\10000) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tb"
    "lChart.coaRef\\100) Mod 100),2) & \"-\" & Right(\"0\" & CStr((tblChart.coaRef) M"
    "od 100),2)) AS coaRef, tblChart.lvlID, qryTrialProfitLoss2.accID, qryTrialProfit"
    "Loss2.Bal, qryTrialProfitLoss2.accNo, qryTrialProfitLoss2.accName\015\012FROM tb"
    "lChart INNER JOIN qryTrialProfitLoss2 ON tblChart.coaRef=qryTrialProfitLoss2.coa"
    "Ref\015\012WHERE tblChart.lvlID=Forms.frmReport.txtToStr2\015\012ORDER BY tblCha"
    "rt.coaRef;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
    Begin
        dbText "Name" ="coaRef"
    End
End
