dbMemo "SQL" ="SELECT qryStatTrialBal3.accNo, qryStatTrialBal3.accName, qryStatTrialBal3.Bal, q"
    "ryStatementTrns.trnEntryDate, qryStatementTrns.trnsDebits, qryStatementTrns.trns"
    "Credits, qryStatementTrns.trnInternalRef, qryStatementTrns.refName, qryStatement"
    "Trns.desName, qryStatementTrns.trnsDate, qryStatementTrns.yearID, qryStatementTr"
    "ns.persID, qryStatementTrns.trnsNote, qryStatTrialBal3.CR, qryStatTrialBal3.DR, "
    "qryStatTrialBal3.OpenBalDR, qryStatTrialBal3.OpenBalCR, qryChartWithAccountsVAT."
    "VatType\015\012FROM qryChartWithAccountsVAT INNER JOIN (qryStatementTrns RIGHT J"
    "OIN qryStatTrialBal3 ON qryStatementTrns.accID=qryStatTrialBal3.accID) ON qryCha"
    "rtWithAccountsVAT.accNo=qryStatTrialBal3.accNo\015\012WHERE (((qryStatTrialBal3."
    "accNo)>'' And (qryStatTrialBal3.accNo) Between Forms.frmReport.cboFromStr1 And F"
    "orms.frmReport.cboToStr1))\015\012ORDER BY qryChartWithAccountsVat.VatType, qryS"
    "tatTrialBal3.accNo;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
