dbMemo "SQL" ="SELECT qryBalanceSheet2.coaID, qryBalanceSheet2.coaNo, qryBalanceSheet2.coaName,"
    " qryBalanceSheet2.coaFRef, qryBalanceSheet2.coaRef, qryBalanceSheet2.lvlID, qryB"
    "alanceSheet2.accID, qryBalanceSheet2.Bal, qryBalanceSheet2.CR, qryBalanceSheet2."
    "DR, qryBalanceSheet2.OpenBalCR, qryBalanceSheet2.OpenBalDR, qryBalanceSheet2.acc"
    "No, qryBalanceSheet2.accName, qryBalanceSheet2.accType\015\012FROM qryBalanceShe"
    "et2\015\012UNION ALL SELECT '' As coaID, '' As coaNo, 'Profit&Loss' As coaName, "
    "'99-99-99-99-999' As coaFRef, '' As coaRef, '5' As lvlID, '' As accID, Sum(qryTr"
    "ialProfitLoss3.Bal) AS Bal, IIf(Sum(qryTrialProfitLoss3.DR)-Sum(qryTrialProfitLo"
    "ss3.CR)<0,Abs(Sum(qryTrialProfitLoss3.DR)-Sum(qryTrialProfitLoss3.CR)), 0) AS CR"
    ", IIf(Sum(qryTrialProfitLoss3.DR)-Sum(qryTrialProfitLoss3.CR)>=0,Sum(qryTrialPro"
    "fitLoss3.DR)-Sum(qryTrialProfitLoss3.CR), 0) AS DR, Sum(qryTrialProfitLoss3.Open"
    "BalCR), Sum(qryTrialProfitLoss3.OpenBalDR),  '' As accNo, 'Profit&Loss' As accNa"
    "me, '1' As accType\015\012FROM qryTrialProfitLoss3;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
