dbMemo "SQL" ="SELECT tblChart.coaID, tblChart.lvlID, tblChart.coaIDg, tblChart.coaNo, tblChart"
    ".coaName, tblChart.coaRef1, tblChart.coaRef2, tblChart.coaRef3, tblChart.coaRef4"
    ", tblChart.coaRef5, tblAccount.accNo, tblAccount.accName, tblAccount.accID, tblA"
    "ccount.accIsVat, tblAccount.accType, tblAccount.accOpenBalance, tblAccount.accTy"
    "pe\015\012FROM tblChart LEFT JOIN tblAccount ON tblChart.coaID=tblAccount.caoID\015"
    "\012WHERE tblAccount.accType=2;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
