dbMemo "SQL" ="SELECT qryStatementAllTrns.trnsID, qryStatAllTrialBal3.accNo, qryStatAllTrialBal"
    "3.accName, (qryStatAllTrialBal3.DR+ qryStatAllTrialBal3.OpenBalDR- qryStatAllTri"
    "alBal3.OpenBalCR-qryStatAllTrialBal3.CR) AS Bal, qryStatAllTrialBal3.Bal AS OBal"
    ", qryStatAllTrialBal3.FBal, qryStatementAllTrns.trnsDocDate, qryStatementAllTrns"
    ".trnEntryDate, qryStatementAllTrns.trnsDebits, qryStatementAllTrns.trnsCredits, "
    "qryStatementAllTrns.trnsFDebits, qryStatementAllTrns.trnsFCredits, qryStatementA"
    "llTrns.trnInternalRef, qryStatementAllTrns.refName, qryStatementAllTrns.desName,"
    " qryStatementAllTrns.trnsDate, qryStatementAllTrns.yearID, qryStatementAllTrns.p"
    "ersID, qryStatementAllTrns.trnsNote, qryStatAllTrialBal3.CR, qryStatAllTrialBal3"
    ".DR, qryStatAllTrialBal3.OpenBalDR, qryStatAllTrialBal3.OpenBalCR, qryStatAllTri"
    "alBal3.FCR, qryStatAllTrialBal3.FDR, qryStatAllTrialBal3.FOpenBalDR, qryStatAllT"
    "rialBal3.FOpenBalCR, qryStatementAllTrns.docNo, qryStatAllTrialBal3.accCur, qryS"
    "tatementAllTrns.trnsVID\015\012FROM qryStatementAllTrns RIGHT JOIN qryStatAllTri"
    "alBal3 ON qryStatementAllTrns.accID=qryStatAllTrialBal3.accID\015\012WHERE (((qr"
    "yStatAllTrialBal3.accNo)>'' And (qryStatAllTrialBal3.accNo) Between Forms.frmRep"
    "ort.cboFromStr1 And Forms.frmReport.cboToStr1))\015\012ORDER BY qryStatAllTrialB"
    "al3.accNo;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
