dbMemo "SQL" ="SELECT qryStatementTrns.trnsID, qryStatTrialBal3.accNo, qryStatTrialBal3.accName"
    ", qryStatTrialBal3.Bal, qryStatementTrns.trnsDocDate, qryStatementTrns.trnEntryD"
    "ate, qryStatementTrns.trnsDebits, qryStatementTrns.trnsCredits, qryStatementTrns"
    ".trnInternalRef, qryStatementTrns.refName, qryStatementTrns.desName, qryStatemen"
    "tTrns.trnsDate, qryStatementTrns.yearID, qryStatementTrns.persID, qryStatementTr"
    "ns.trnsNote, qryStatTrialBal3.CR, qryStatTrialBal3.DR, qryStatTrialBal3.OpenBalD"
    "R, qryStatTrialBal3.OpenBalCR, qryStatementTrns.docNo\015\012FROM qryStatementTr"
    "ns RIGHT JOIN qryStatTrialBal3 ON qryStatementTrns.accID=qryStatTrialBal3.accID\015"
    "\012WHERE (((qryStatTrialBal3.accNo)>'' And (qryStatTrialBal3.accNo) Between For"
    "ms.frmReport.cboFromStr1 And Forms.frmReport.cboToStr1))\015\012ORDER BY qryStat"
    "TrialBal3.accNo;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
