dbMemo "SQL" ="SELECT Sum(IIf([trnsSign]='C',-1*[trnsAmount],[trnsAmount])) AS Bal, tblControl."
    "ctrLYPLA\015\012FROM tblControl, (prevtblAccount INNER JOIN (prevtblTransactionS"
    "ub INNER JOIN prevtblTransaction ON prevtblTransactionSub.trnID = prevtblTransac"
    "tion.trnID) ON prevtblAccount.accID = prevtblTransactionSub.accID) INNER JOIN tb"
    "lAccount ON prevtblAccount.accID = tblAccount.accID\015\012WHERE (((prevtblTrans"
    "action.trnYear) In (SELECT yearID FROM prevtblControl)) AND ((prevtblAccount.acc"
    "Type)=1))\015\012GROUP BY tblControl.ctrLYPLA;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
