dbMemo "SQL" ="SELECT nz(tblControl.ctrLYPLA,0) AS ctrLYPLA, nz(tblControl.ctrControlAcc,0) AS "
    "ctrControlAcc, nz(tblControl.ctrInvCR,0) AS ctrInvCR, nz(tblControl.ctrCRN_DR,0)"
    " AS ctrCRN_DR, nz(tblControl.ctrDRN_CR,0) AS ctrDRN_CR, nz(tblControl.ctrRcptDR,"
    "0) AS ctrRcptDR, nz(tblControl.ctrExpDR,0) AS ctrExpDR, nz(tblControl.ctrPaymtCR"
    ",0) AS ctrPaymtCR, nz(tblControl.ctrDeptsCR,0) AS ctrDeptsCR, nz(tblControl.ctrC"
    "shWithdrwCR,0) AS ctrCshWithdrwCR\015\012FROM tblControl;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
Begin
End
